version: '3'
services:
  flink_ueba_manager:
    image: "monstertau/flink_ueba_manager:v0.0.1"
    container_name: flink_ueba_manager
    #    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    ports:
      - "9098:9098"
#    volumes:
#      - ./config.yaml:/money-core/config.yaml
networks:
  default:
    external:
      name: docker-helk